DEFS     += -fPIC
INCLUDES += -I/usr/include/libxml2 -I/usr/local/include/libxml2 -I/usr/include/curl -I/usr/local/include -I../../ -I../cds/ -I../../mem/ 
LIBS     += -L/usr/local/lib -L../cds -lxml2 -lcds -lcurl

# name of result executable or library
NAME = lost_client

# TYPE=lib => shared or static library, executable otherwise
TYPE = lib

include ../Makefile.defs

